algorithm:
  paradigm: "lifelonglearning"
  dataset_train_ratio: 0.8
  modules:
    - kind: "basemodel"
      name: "estimator"
      url: "/home/yj/ianvs/examples/pcb/algorithms/basemodel.py"
      hyperparameters:
        - other_hyperparameters:
            values:
              - "/home/yj/ianvs/examples/pcb/config/hyperparameter.yaml"
    - kind: "task_definition"
      name: "TaskDefinitionByCluster"
      hyperparameters:
        - n_class:
            values:
              - 1
    # inference parameters
    - kind: "task_division"
      name: "TaskDivisionByAttr"
    - kind: "unseen_task_detect"
      name: "FMeasureFilter"
      hyperparameters:
        - estimator:
            values:
              - "basemodel"
    - kind: "inference_integrate"
      name: "BBoxInferenceIntegrate"
    # update training parameters
    - kind: "task_process"
      name: "ProcessByModelMining"
    - kind: "unseen_task_division"
      name: "TaskDivisionByModelProbe"
    - kind: "unseen_task_process"
      name: "ProcessByModelMining"
    - kind: "task_update_strategy"
      name: "UpdateStrategyByModelMining"