# 测试环境配置（考官出考卷）
testenv:
  # 数据配置
  dataset:
    # 数据地址， 字符串类型， 必填， 默认值是 ""；
    # 当前支持数据文件格式有csv(结构化数据）、txt(非结构化数据）；
    # todo: 暴露接口，支持用户自定义数据格式转换；
    url: "/home/yj/ianvs/examples/atcii/trainData.csv"
    # 模型训练的标签， 列表类型， 必填，当前与
    label: "Thermal preference"
    # 模型训练数据集比例， 浮点类型， 可选，默认值是 0.8；
    train_ratio: 0.8
    # 数据拆分方式，字符串类型， 可选，默认值是 "default"
    # "default"方法： 数据列表按照eval_ratio比例切分；
    splitting_method: "default"

  # 同个算法单个模型的评估配置，字典类型，可选，默认值是 {} ；
  # 可选，仅用于终身学习范式的评估阶段：筛选给定算法训练后的任务模型，仅把筛选出的任务模型传递给推理阶段，其它任务模型不传递
  # 也即在边云协同推理、联邦学习、增量学习范式无需填写下列配置
  model_eval:
    # 模型评估的指标计算方法， 字典类型, 可选， 默认值是 {} ；
    # 模型的评估指标计算方法。仅使用唯一指标进行评估和模型筛选，暂不支持容易导致系统混乱的多指标评估。
    # 支持使用lib中内置的指标计算方法，详细见lib库；
    # 支持自定义指标计算方法；
    model_metric:
      # 指标计算方法名，字符串类型, 必选， 默认值是""；
      name: "precision_score"
      # 自定义指标计算方法文件， 字符串类型，可选，默认值是""；
      # url: "/home/yj/ianvs/examples/fpn/algorithms/f1_score.py"
      # 模型评估的指标计算方法的入参， 字典类型， 可选， 默认值是 {} ；
      parameters: { average: "micro" }
    # 评估指标的阈值，浮点类型， 可选， 默认值是 0.9 ；
    threashold: 0.1
    # 指标结果和阈值之间的关系操作，支持">", "<", "="等关系字符串
    # 即小于此阈值的任务模型将被传递到推理阶段，否则不传递
    operator: "<"

  # ianvs评估的指标计算方法，列表类型， 必填；
  # 单个算法的评估指标。注：在终身学习中单个算法可能产生多个模型，此处为单个算法多个模型的端到端评估指标
  # 可以填写希望显示的多个指标，指标按照列举先后顺序作为优先级排序，比如列在前面的优先级更高
  # 支持使用内置的指标计算方法，当前metrics.py内置支持 "smape" 和 "max_error_rate"；
  # 支持自定义指标计算方法；
  metrics:
    # 指标计算方法名，字符串类型, 必选， 默认值是""；
    - name: "smape"
      # 自定义指标计算方法文件， 字符串类型，可选，默认值是""；
      # url: "/home/yj/ianvs/examples/fpn/algorithms/f1_score.py"

  # 终身学习范式和增量学习范式支持增量轮次配置, 整数类型，可选， 默认值是 1 ；
  # 增量轮次是指除初始轮次外的补充轮次，根据增量轮次和初始轮次平均分配训练数据
  # 比如训练数据除初始轮次外有1轮增量，则初始轮次、首次增量轮次，最终增量轮次各得到1/2训练数据；
  incremental_rounds: 1