algorithm:
  paradigm: "incrementallearning"
  dataset_train_ratio: 0.8
  initial_model_url: "/ianvs/pcb-aoi/initial_model/model.zip"
  modules:
    - kind: "basemodel"
      name: "estimator"
      url: "/home/yj/ianvs/examples/pcb-aoi/algorithms/basemodel.py"
      hyperparameters:
        - other_hyperparameters:
            values:
              - "/home/yj/ianvs/examples/pcb-aoi/config/hyperparameter.yaml"